name: CI

on:
  schedule:
    - cron:  '0 0 * * 0'  # every Sunday at midnight
  workflow_dispatch:  # For manual triggering
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Whether to stop execution of other instances
      max-parallel: 4
      matrix:
        os: ["ubuntu-latest"]#, "windows-latest"]  #  , "macos-latest"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Setup env (Windows)
        run: |
          set "NODE_ENV=testing"
          set "DOTENV_CONFIG_PATH=./test/fixtures/.env.test"
        if: matrix.os == 'windows-latest'
      - name: Setup env (Linux)
        run: |
          NODE_ENV=testing
          DOTENV_CONFIG_PATH=./test/fixtures/.env.test
        if: matrix.os == 'ubuntu-latest'
      - name: Run tests
        run: |
          ls -a $(dirname $DOTENV_CONFIG_PATH)
          npm test
